version: "3.6"
services:
  redalert:
    image: techblog/redalert
    container_name: redalert
    restart: always
    environment:
      - MQTT_HOST=[Broker Address]
      - MQTT_USER=[Broker Username]
      - MQTT_PASS=[Broker Password]
      - DEBUG_MODE=False
      - REGION=[* for any or region name)
      - NOTIFIERS=[Apprise notifiers]
      - INCLUDE_TEST_ALERTS=[False|True]
      - GREEN_API_INSTANCE = #GREEN_API_INSTANCE
      - GREEN_API_TOKEN = #GREEN_API_TOKEN
      - WHATSAPP_NUMBER = #WHATSAPP_NUMBER
